# Generated by Django 4.1.7 on 2023-05-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("businessdashboard", "0002_menu_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
