# Generated by Django 4.1.7 on 2023-03-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessionmanager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eatery',
        ),
    ]
