# Generated by Django 4.1.7 on 2023-04-27 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(default="default.svg", upload_to="profile_pics"),
                ),
                (
                    "preffered_genres",
                    models.ManyToManyField(to="userdashboard.foodgenre"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Eatery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eatery_name", models.CharField(max_length=100)),
                ("details", models.TextField(blank=True)),
                ("location", models.CharField(default="", max_length=200)),
                (
                    "logo",
                    models.ImageField(
                        default="eatery_logos/default.png", upload_to="eatery_logos"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        default="eatery_banners/banner.jpg", upload_to="eatery_banners"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("food_genres", models.ManyToManyField(to="userdashboard.foodgenre")),
            ],
        ),
    ]
