# Generated by Django 4.1.7 on 2023-03-16 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eatery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eatery_name', models.CharField(max_length=100)),
                ('food_genre', models.CharField(default='', max_length=200)),
                ('details', models.TextField()),
                ('location', models.CharField(default='', max_length=200)),
                ('logo', models.ImageField(default='default.jpg', upload_to='media')),
                ('banner', models.ImageField(default='banner.jpg', upload_to='media')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
