# Generated by Django 4.1.7 on 2023-03-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatery',
            name='banner',
            field=models.ImageField(default='banner.jpg', upload_to='eatery_banners'),
        ),
        migrations.AlterField(
            model_name='eatery',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='eatery_logos'),
        ),
    ]
