# Generated by Django 4.1.7 on 2023-04-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdashboard", "0002_profile_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="eatery",
            name="food_genre",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
