# Generated by Django 4.1.7 on 2023-04-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='preffered_genres',
            field=models.ManyToManyField(to='userdashboard.foodgenre'),
        ),
    ]
