# Generated by Django 4.1.7 on 2023-05-25 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0006_remove_eatery_menu_items_menu_eatery'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eatery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdashboard.eatery'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='eatery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='userdashboard.eatery'),
        ),
    ]
