# Generated by Django 4.1.7 on 2023-05-25 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0008_alter_profile_preffered_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('comment', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdashboard.eatery')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdashboard.profile')),
            ],
        ),
    ]
