# Generated by Django 4.1.7 on 2023-05-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userdashboard", "0009_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="eatery",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="userdashboard.eatery",
            ),
        ),
    ]
